// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package org.pd.domain;

public final class DataProto {
  private DataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.CommonResult commentResult = 1;</code>
     * @return Whether the commentResult field is set.
     */
    boolean hasCommentResult();
    /**
     * <code>.proto.CommonResult commentResult = 1;</code>
     * @return The commentResult.
     */
    org.pd.domain.DataProto.CommonResult getCommentResult();
    /**
     * <code>.proto.CommonResult commentResult = 1;</code>
     */
    org.pd.domain.DataProto.CommonResultOrBuilder getCommentResultOrBuilder();
  }
  /**
   * Protobuf type {@code proto.Data}
   */
  public static final class Data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Data)
      DataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Data() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Data();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.pd.domain.DataProto.internal_static_proto_Data_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.pd.domain.DataProto.internal_static_proto_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.pd.domain.DataProto.Data.class, org.pd.domain.DataProto.Data.Builder.class);
    }

    public static final int COMMENTRESULT_FIELD_NUMBER = 1;
    private org.pd.domain.DataProto.CommonResult commentResult_;
    /**
     * <code>.proto.CommonResult commentResult = 1;</code>
     * @return Whether the commentResult field is set.
     */
    @java.lang.Override
    public boolean hasCommentResult() {
      return commentResult_ != null;
    }
    /**
     * <code>.proto.CommonResult commentResult = 1;</code>
     * @return The commentResult.
     */
    @java.lang.Override
    public org.pd.domain.DataProto.CommonResult getCommentResult() {
      return commentResult_ == null ? org.pd.domain.DataProto.CommonResult.getDefaultInstance() : commentResult_;
    }
    /**
     * <code>.proto.CommonResult commentResult = 1;</code>
     */
    @java.lang.Override
    public org.pd.domain.DataProto.CommonResultOrBuilder getCommentResultOrBuilder() {
      return getCommentResult();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (commentResult_ != null) {
        output.writeMessage(1, getCommentResult());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (commentResult_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCommentResult());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.pd.domain.DataProto.Data)) {
        return super.equals(obj);
      }
      org.pd.domain.DataProto.Data other = (org.pd.domain.DataProto.Data) obj;

      if (hasCommentResult() != other.hasCommentResult()) return false;
      if (hasCommentResult()) {
        if (!getCommentResult()
            .equals(other.getCommentResult())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCommentResult()) {
        hash = (37 * hash) + COMMENTRESULT_FIELD_NUMBER;
        hash = (53 * hash) + getCommentResult().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.pd.domain.DataProto.Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.pd.domain.DataProto.Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.pd.domain.DataProto.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.pd.domain.DataProto.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.pd.domain.DataProto.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.pd.domain.DataProto.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.pd.domain.DataProto.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.pd.domain.DataProto.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.pd.domain.DataProto.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.pd.domain.DataProto.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.pd.domain.DataProto.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.pd.domain.DataProto.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.pd.domain.DataProto.Data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Data)
        org.pd.domain.DataProto.DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.pd.domain.DataProto.internal_static_proto_Data_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.pd.domain.DataProto.internal_static_proto_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.pd.domain.DataProto.Data.class, org.pd.domain.DataProto.Data.Builder.class);
      }

      // Construct using org.pd.domain.DataProto.Data.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (commentResultBuilder_ == null) {
          commentResult_ = null;
        } else {
          commentResult_ = null;
          commentResultBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.pd.domain.DataProto.internal_static_proto_Data_descriptor;
      }

      @java.lang.Override
      public org.pd.domain.DataProto.Data getDefaultInstanceForType() {
        return org.pd.domain.DataProto.Data.getDefaultInstance();
      }

      @java.lang.Override
      public org.pd.domain.DataProto.Data build() {
        org.pd.domain.DataProto.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.pd.domain.DataProto.Data buildPartial() {
        org.pd.domain.DataProto.Data result = new org.pd.domain.DataProto.Data(this);
        if (commentResultBuilder_ == null) {
          result.commentResult_ = commentResult_;
        } else {
          result.commentResult_ = commentResultBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.pd.domain.DataProto.Data) {
          return mergeFrom((org.pd.domain.DataProto.Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.pd.domain.DataProto.Data other) {
        if (other == org.pd.domain.DataProto.Data.getDefaultInstance()) return this;
        if (other.hasCommentResult()) {
          mergeCommentResult(other.getCommentResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getCommentResultFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 10
              default: {
               // if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
//                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private org.pd.domain.DataProto.CommonResult commentResult_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.pd.domain.DataProto.CommonResult, org.pd.domain.DataProto.CommonResult.Builder, org.pd.domain.DataProto.CommonResultOrBuilder> commentResultBuilder_;
      /**
       * <code>.proto.CommonResult commentResult = 1;</code>
       * @return Whether the commentResult field is set.
       */
      public boolean hasCommentResult() {
        return commentResultBuilder_ != null || commentResult_ != null;
      }
      /**
       * <code>.proto.CommonResult commentResult = 1;</code>
       * @return The commentResult.
       */
      public org.pd.domain.DataProto.CommonResult getCommentResult() {
        if (commentResultBuilder_ == null) {
          return commentResult_ == null ? org.pd.domain.DataProto.CommonResult.getDefaultInstance() : commentResult_;
        } else {
          return commentResultBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.CommonResult commentResult = 1;</code>
       */
      public Builder setCommentResult(org.pd.domain.DataProto.CommonResult value) {
        if (commentResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          commentResult_ = value;
          onChanged();
        } else {
          commentResultBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.CommonResult commentResult = 1;</code>
       */
      public Builder setCommentResult(
          org.pd.domain.DataProto.CommonResult.Builder builderForValue) {
        if (commentResultBuilder_ == null) {
          commentResult_ = builderForValue.build();
          onChanged();
        } else {
          commentResultBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.CommonResult commentResult = 1;</code>
       */
      public Builder mergeCommentResult(org.pd.domain.DataProto.CommonResult value) {
        if (commentResultBuilder_ == null) {
          if (commentResult_ != null) {
            commentResult_ =
              org.pd.domain.DataProto.CommonResult.newBuilder(commentResult_).mergeFrom(value).buildPartial();
          } else {
            commentResult_ = value;
          }
          onChanged();
        } else {
          commentResultBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.CommonResult commentResult = 1;</code>
       */
      public Builder clearCommentResult() {
        if (commentResultBuilder_ == null) {
          commentResult_ = null;
          onChanged();
        } else {
          commentResult_ = null;
          commentResultBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.CommonResult commentResult = 1;</code>
       */
      public org.pd.domain.DataProto.CommonResult.Builder getCommentResultBuilder() {
        
        onChanged();
        return getCommentResultFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.CommonResult commentResult = 1;</code>
       */
      public org.pd.domain.DataProto.CommonResultOrBuilder getCommentResultOrBuilder() {
        if (commentResultBuilder_ != null) {
          return commentResultBuilder_.getMessageOrBuilder();
        } else {
          return commentResult_ == null ?
              org.pd.domain.DataProto.CommonResult.getDefaultInstance() : commentResult_;
        }
      }
      /**
       * <code>.proto.CommonResult commentResult = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.pd.domain.DataProto.CommonResult, org.pd.domain.DataProto.CommonResult.Builder, org.pd.domain.DataProto.CommonResultOrBuilder> 
          getCommentResultFieldBuilder() {
        if (commentResultBuilder_ == null) {
          commentResultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.pd.domain.DataProto.CommonResult, org.pd.domain.DataProto.CommonResult.Builder, org.pd.domain.DataProto.CommonResultOrBuilder>(
                  getCommentResult(),
                  getParentForChildren(),
                  isClean());
          commentResult_ = null;
        }
        return commentResultBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Data)
    }

    // @@protoc_insertion_point(class_scope:proto.Data)
    private static final org.pd.domain.DataProto.Data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.pd.domain.DataProto.Data();
    }

    public static org.pd.domain.DataProto.Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Data>
        PARSER = new com.google.protobuf.AbstractParser<Data>() {
      @java.lang.Override
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.pd.domain.DataProto.Data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CommonResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.CommonResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 errCode = 1;</code>
     * @return The errCode.
     */
    int getErrCode();

    /**
     * <pre>
     * 错误内容
     * </pre>
     *
     * <code>string errMsg = 2;</code>
     * @return The errMsg.
     */
    java.lang.String getErrMsg();
    /**
     * <pre>
     * 错误内容
     * </pre>
     *
     * <code>string errMsg = 2;</code>
     * @return The bytes for errMsg.
     */
    com.google.protobuf.ByteString
        getErrMsgBytes();

    /**
     * <pre>
     * 扩展字段
     * </pre>
     *
     * <code>string flag = 3;</code>
     * @return The flag.
     */
    java.lang.String getFlag();
    /**
     * <pre>
     * 扩展字段
     * </pre>
     *
     * <code>string flag = 3;</code>
     * @return The bytes for flag.
     */
    com.google.protobuf.ByteString
        getFlagBytes();
  }
  /**
   * Protobuf type {@code proto.CommonResult}
   */
  public static final class CommonResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.CommonResult)
      CommonResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommonResult.newBuilder() to construct.
    private CommonResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommonResult() {
      errMsg_ = "";
      flag_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CommonResult();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.pd.domain.DataProto.internal_static_proto_CommonResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.pd.domain.DataProto.internal_static_proto_CommonResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.pd.domain.DataProto.CommonResult.class, org.pd.domain.DataProto.CommonResult.Builder.class);
    }

    public static final int ERRCODE_FIELD_NUMBER = 1;
    private int errCode_;
    /**
     * <code>int32 errCode = 1;</code>
     * @return The errCode.
     */
    @java.lang.Override
    public int getErrCode() {
      return errCode_;
    }

    public static final int ERRMSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object errMsg_;
    /**
     * <pre>
     * 错误内容
     * </pre>
     *
     * <code>string errMsg = 2;</code>
     * @return The errMsg.
     */
    @java.lang.Override
    public java.lang.String getErrMsg() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errMsg_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 错误内容
     * </pre>
     *
     * <code>string errMsg = 2;</code>
     * @return The bytes for errMsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErrMsgBytes() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FLAG_FIELD_NUMBER = 3;
    private volatile java.lang.Object flag_;
    /**
     * <pre>
     * 扩展字段
     * </pre>
     *
     * <code>string flag = 3;</code>
     * @return The flag.
     */
    @java.lang.Override
    public java.lang.String getFlag() {
      java.lang.Object ref = flag_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        flag_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 扩展字段
     * </pre>
     *
     * <code>string flag = 3;</code>
     * @return The bytes for flag.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFlagBytes() {
      java.lang.Object ref = flag_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        flag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errCode_ != 0) {
        output.writeInt32(1, errCode_);
      }
      if (!getErrMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errMsg_);
      }
      if (!getFlagBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, flag_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errCode_);
      }
      if (!getErrMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errMsg_);
      }
      if (!getFlagBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, flag_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.pd.domain.DataProto.CommonResult)) {
        return super.equals(obj);
      }
      org.pd.domain.DataProto.CommonResult other = (org.pd.domain.DataProto.CommonResult) obj;

      if (getErrCode()
          != other.getErrCode()) return false;
      if (!getErrMsg()
          .equals(other.getErrMsg())) return false;
      if (!getFlag()
          .equals(other.getFlag())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrCode();
      hash = (37 * hash) + ERRMSG_FIELD_NUMBER;
      hash = (53 * hash) + getErrMsg().hashCode();
      hash = (37 * hash) + FLAG_FIELD_NUMBER;
      hash = (53 * hash) + getFlag().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.pd.domain.DataProto.CommonResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.pd.domain.DataProto.CommonResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.pd.domain.DataProto.CommonResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.pd.domain.DataProto.CommonResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.pd.domain.DataProto.CommonResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.pd.domain.DataProto.CommonResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.pd.domain.DataProto.CommonResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.pd.domain.DataProto.CommonResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.pd.domain.DataProto.CommonResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.pd.domain.DataProto.CommonResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.pd.domain.DataProto.CommonResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.pd.domain.DataProto.CommonResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.pd.domain.DataProto.CommonResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.CommonResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.CommonResult)
        org.pd.domain.DataProto.CommonResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.pd.domain.DataProto.internal_static_proto_CommonResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.pd.domain.DataProto.internal_static_proto_CommonResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.pd.domain.DataProto.CommonResult.class, org.pd.domain.DataProto.CommonResult.Builder.class);
      }

      // Construct using org.pd.domain.DataProto.CommonResult.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        errCode_ = 0;

        errMsg_ = "";

        flag_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.pd.domain.DataProto.internal_static_proto_CommonResult_descriptor;
      }

      @java.lang.Override
      public org.pd.domain.DataProto.CommonResult getDefaultInstanceForType() {
        return org.pd.domain.DataProto.CommonResult.getDefaultInstance();
      }

      @java.lang.Override
      public org.pd.domain.DataProto.CommonResult build() {
        org.pd.domain.DataProto.CommonResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.pd.domain.DataProto.CommonResult buildPartial() {
        org.pd.domain.DataProto.CommonResult result = new org.pd.domain.DataProto.CommonResult(this);
        result.errCode_ = errCode_;
        result.errMsg_ = errMsg_;
        result.flag_ = flag_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.pd.domain.DataProto.CommonResult) {
          return mergeFrom((org.pd.domain.DataProto.CommonResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.pd.domain.DataProto.CommonResult other) {
        if (other == org.pd.domain.DataProto.CommonResult.getDefaultInstance()) return this;
        if (other.getErrCode() != 0) {
          setErrCode(other.getErrCode());
        }
        if (!other.getErrMsg().isEmpty()) {
          errMsg_ = other.errMsg_;
          onChanged();
        }
        if (!other.getFlag().isEmpty()) {
          flag_ = other.flag_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                errCode_ = input.readInt32();

                break;
              } // case 8
              case 18: {
                errMsg_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 26: {
                flag_ = input.readStringRequireUtf8();

                break;
              } // case 26
              default: {
                //if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
//                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int errCode_ ;
      /**
       * <code>int32 errCode = 1;</code>
       * @return The errCode.
       */
      @java.lang.Override
      public int getErrCode() {
        return errCode_;
      }
      /**
       * <code>int32 errCode = 1;</code>
       * @param value The errCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrCode(int value) {
        
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 errCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrCode() {
        
        errCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errMsg_ = "";
      /**
       * <pre>
       * 错误内容
       * </pre>
       *
       * <code>string errMsg = 2;</code>
       * @return The errMsg.
       */
      public java.lang.String getErrMsg() {
        java.lang.Object ref = errMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 错误内容
       * </pre>
       *
       * <code>string errMsg = 2;</code>
       * @return The bytes for errMsg.
       */
      public com.google.protobuf.ByteString
          getErrMsgBytes() {
        java.lang.Object ref = errMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 错误内容
       * </pre>
       *
       * <code>string errMsg = 2;</code>
       * @param value The errMsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误内容
       * </pre>
       *
       * <code>string errMsg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrMsg() {
        
        errMsg_ = getDefaultInstance().getErrMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误内容
       * </pre>
       *
       * <code>string errMsg = 2;</code>
       * @param value The bytes for errMsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errMsg_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object flag_ = "";
      /**
       * <pre>
       * 扩展字段
       * </pre>
       *
       * <code>string flag = 3;</code>
       * @return The flag.
       */
      public java.lang.String getFlag() {
        java.lang.Object ref = flag_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          flag_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 扩展字段
       * </pre>
       *
       * <code>string flag = 3;</code>
       * @return The bytes for flag.
       */
      public com.google.protobuf.ByteString
          getFlagBytes() {
        java.lang.Object ref = flag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          flag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 扩展字段
       * </pre>
       *
       * <code>string flag = 3;</code>
       * @param value The flag to set.
       * @return This builder for chaining.
       */
      public Builder setFlag(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        flag_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 扩展字段
       * </pre>
       *
       * <code>string flag = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFlag() {
        
        flag_ = getDefaultInstance().getFlag();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 扩展字段
       * </pre>
       *
       * <code>string flag = 3;</code>
       * @param value The bytes for flag to set.
       * @return This builder for chaining.
       */
      public Builder setFlagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        flag_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.CommonResult)
    }

    // @@protoc_insertion_point(class_scope:proto.CommonResult)
    private static final org.pd.domain.DataProto.CommonResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.pd.domain.DataProto.CommonResult();
    }

    public static org.pd.domain.DataProto.CommonResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommonResult>
        PARSER = new com.google.protobuf.AbstractParser<CommonResult>() {
      @java.lang.Override
      public CommonResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CommonResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommonResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.pd.domain.DataProto.CommonResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Data_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CommonResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CommonResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndata.proto\022\005proto\"2\n\004Data\022*\n\rcommentRe" +
      "sult\030\001 \001(\0132\023.proto.CommonResult\"=\n\014Commo" +
      "nResult\022\017\n\007errCode\030\001 \001(\005\022\016\n\006errMsg\030\002 \001(\t" +
      "\022\014\n\004flag\030\003 \001(\tB\034\n\rorg.pd.domainB\tDataPro" +
      "toP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_Data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Data_descriptor,
        new java.lang.String[] { "CommentResult", });
    internal_static_proto_CommonResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_CommonResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CommonResult_descriptor,
        new java.lang.String[] { "ErrCode", "ErrMsg", "Flag", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
